/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vues;

import Entity.Employe;
import Entity.Rayon;
import Entity.Secteur;
import Entity.Travailler;
import Tools.ConnexionBDD;
import Tools.FonctionsMetier;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jacqu
 */
public class FrmPrincipal extends javax.swing.JFrame {

    ConnexionBDD cnx;
    FonctionsMetier fm;
    
    DefaultTableModel dtmSecteurs;
    DefaultTableModel dtmRayons;
    DefaultTableModel dtmEmployes;
    Vector v;
    
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecteurs = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRayons = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEmployes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalHeuresRayon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNouveauTemps = new javax.swing.JTextField();
        btnModifier = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cboEmployes = new javax.swing.JComboBox<>();
        btnInsererTemps = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Les secteurs");

        jLabel2.setText("Les rayons");

        jLabel3.setText("Les employés");

        tblSecteurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom"
            }
        ));
        tblSecteurs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSecteursMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSecteurs);

        tblRayons.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Nom"
            }
        ));
        tblRayons.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRayonsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRayons);

        tblEmployes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro", "Prénom", "Date", "Temps"
            }
        ));
        jScrollPane3.setViewportView(tblEmployes);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gestion Supermarché");

        jLabel5.setText("Total des heures du rayon");

        txtTotalHeuresRayon.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel6.setText("Nouveau temps");

        txtNouveauTemps.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnModifier.setText("Modifier");
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifierMouseClicked(evt);
            }
        });

        jLabel7.setText("Les  employés");

        btnInsererTemps.setText("Insérer un nouveau temps");
        btnInsererTemps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsererTempsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(btnInsererTemps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNouveauTemps, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(txtTotalHeuresRayon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifier))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTotalHeuresRayon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNouveauTemps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier)
                    .addComponent(btnInsererTemps))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        dtmSecteurs = (DefaultTableModel)tblSecteurs.getModel();
        
        
        cnx=new ConnexionBDD();
        fm=new FonctionsMetier();
        
        for(Secteur unSecteur : fm.GetAllSecteurs())
        {
            v = new Vector();
            v.add(unSecteur.getIdSecteur());
            v.add(unSecteur.getNomSecteur());
            dtmSecteurs.addRow(v);
        }
        tblSecteurs.setModel(dtmSecteurs);
        
        for(Employe em : fm.GetAllEmployes())
        {
            cboEmployes.addItem(em.getNomEmploye());
        }
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tblSecteursMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSecteursMouseClicked

        while(dtmRayons.getRowCount()>0)
        {
            dtmRayons.removeRow(0);
        }
        for (Rayon ra : fm.GetAllRayonsByIdsecteur((int) tblSecteurs.getValueAt(tblSecteurs.getSelectedRow(),0)))
        {
            v = new Vector();
            v.add(ra.getIdRayon());
            v.add(ra.getNomRayon());
            dtmRayons.addRow(v);
             
        }
        tblRayons.setModel(dtmRayons);
        
        
        
    }//GEN-LAST:event_tblSecteursMouseClicked

    private void tblRayonsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRayonsMouseClicked

        while(dtmEmployes.getRowCount()>0)
        {
            dtmEmployes.removeRow(0);
        }
        for (Travailler trav : fm.GetAllTravailler((int) tblRayons.getValueAt(tblRayons.getSelectedRow(),0)))
        {
            v = new Vector();
            v.add(trav.getUnEmploye().getIdEmploye());
            v.add(trav.getUnEmploye().getNomEmploye());
            v.add(trav.getDateTravaillee());
            v.add(trav.getTempsPasse());
            dtmEmployes.addRow(v);
        }
        tblRayons.setModel(dtmRayons);
        txtTotalHeuresRayon.setText(String.valueOf(fm.TotalHeuresRayon((int) tblRayons.getValueAt(tblRayons.getSelectedRow(),0))) );
        
    }//GEN-LAST:event_tblRayonsMouseClicked

    private void btnModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseClicked
        
        if(tblEmployes.getSelectedRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"Sélectionner un employer","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtNouveauTemps.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this,"Saisir un temps","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu-MM-dd"); 
            LocalDate localDate = LocalDate.now(); 
            
            fm.ModifierTemps(tblEmployes.getValueAt(tblEmployes.getSelectedRow(),0), tblRayons.getValueAt(tblRayons.getSelectedRow(),0),dtf.format(localDate), txtNouveauTemps.getText());
            
            while(dtmEmployes.getRowCount()>0)
            {
                dtmEmployes.removeRow(0);
            }
            for (Travailler trav : fm.GetAllTravailler((int) tblRayons.getValueAt(tblRayons.getSelectedRow(),0)))
            {
                v = new Vector();
                v.add(trav.getUnEmploye().getIdEmploye());
                v.add(trav.getUnEmploye().getNomEmploye());
                v.add(trav.getDateTravaillee());
                v.add(trav.getTempsPasse());
                dtmEmployes.addRow(v);
            }
            tblRayons.setModel(dtmRayons);
            txtTotalHeuresRayon.setText(String.valueOf(fm.TotalHeuresRayon((int) tblRayons.getValueAt(tblRayons.getSelectedRow(),0))) );
        }
        
        
        
    }//GEN-LAST:event_btnModifierMouseClicked

    private void btnInsererTempsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsererTempsMouseClicked
        
        if(tblRayons.getSelectedRowCount() == 0)
        {
            JOptionPane.showMessageDialog(this,"Sélectionner un employer","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else if(txtNouveauTemps.getText().compareTo("") == 0)
        {
            JOptionPane.showMessageDialog(this,"Saisir un temps","Erreur de saisie",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            fm.InsererTemps(HIDE_ON_CLOSE, ERROR, SOMEBITS);
        }
        
        
        
    }//GEN-LAST:event_btnInsererTempsMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsererTemps;
    private javax.swing.JButton btnModifier;
    private javax.swing.JComboBox<String> cboEmployes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblEmployes;
    private javax.swing.JTable tblRayons;
    private javax.swing.JTable tblSecteurs;
    private javax.swing.JTextField txtNouveauTemps;
    private javax.swing.JTextField txtTotalHeuresRayon;
    // End of variables declaration//GEN-END:variables
}
